# Generated by Django 2.2 on 2019-04-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=80)),
                ('discount', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('year', models.IntegerField()),
                ('engine', models.CharField(help_text='Двигатель', max_length=100)),
                ('component', models.CharField(help_text='Комплектация', max_length=100)),
                ('color', models.CharField(help_text='Цвет модели', max_length=80)),
            ],
        ),
    ]
