# Generated by Django 2.2 on 2019-04-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_model',
            name='car_name',
        ),
        migrations.RemoveField(
            model_name='car_model',
            name='color',
        ),
        migrations.RemoveField(
            model_name='car_model',
            name='component',
        ),
        migrations.RemoveField(
            model_name='car_model',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='car_model',
            name='year',
        ),
        migrations.AddField(
            model_name='car_model',
            name='car_name_main',
            field=models.CharField(default=3, help_text='Модель', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car_model',
            name='discount',
            field=models.CharField(help_text='Скидка', max_length=20),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='quantity',
            field=models.CharField(default='Остались последние модели!', help_text='Остаток', max_length=40),
        ),
    ]
